background #0f1728
foreground #c0caf5
cursor #6ee65f
cursor_text_color #0f1728
selection_foreground #0f1728
selection_background #6ee65f
url_color #73daca

color0  #0b1220
color8  #3a4a6a
color1  #f7768e
color9  #ff9eaf
color2  #9ece6a
color10 #b9f27c
color3  #e0af68
color11 #ffcf86
color4  #7aa2f7
color12 #8db0ff
color5  #bb9af7
color13 #c7a9ff
color6  #7dcfff
color14 #a4daff
color7  #a9b1d6
color15 #c0caf5

active_border_color   #6ee65f
inactive_border_color #414868

active_tab_foreground   #0f1728
active_tab_background   #6ee65f
inactive_tab_foreground #a9b1d6
inactive_tab_background #162033

tab_bar_background #11192b
tab_bar_margin_color #11192b

mark1_foreground #0f1728
mark1_background #6ee65f
mark2_foreground #0f1728
mark2_background #e0af68
mark3_foreground #0f1728
mark3_background #bb9af7

bell_border_color #e0af68
